### ISSUE TITLE
Bundle of copy changes

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1154]
Copy updates:
- [x] [Update strings for project page](https://github.com/accessibility-exchange/platform/pull/1051) 
- [x] [Update strings for settings page](https://github.com/accessibility-exchange/platform/pull/1058)
- [x] [Update strings for registration page](https://github.com/accessibility-exchange/platform/pull/1059)
- [x] For individuals, under access needs page - "for in-person meetings" heading, please add an additional line right under that reads: "All organizations have been asked to provide gender neutral and accessible washrooms by default." [figma wire](https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1790%3A51698)

Error message updates:
- [x] [Clearer error message for missing "about" on organization page](https://github.com/accessibility-exchange/platform/issues/645)
- [x] [Organization name validation is unclear](https://github.com/accessibility-exchange/platform/issues/659)
- [x] [Error message for Accessibility and Inclusion links could be clearer](https://github.com/accessibility-exchange/platform/issues/671)
